project_id = "njjggyhqddbuzbzibbja"

[functions.generate-and-save-recipe]
verify_jwt = false

[functions.validate-substitution]
verify_jwt = false

[functions.search-recipe]
verify_jwt = false

[functions.get-analytics]
verify_jwt = false

[functions.toggle-analytics-dashboard]
verify_jwt = false
